language: python
sudo: required
python:
- '2.7'
install: 
script: py.test --cov arfcnreference
after_success:
- codeclimate-test-reporter --token $CODECLIMATE_REPO_TOKEN
env:
  global:
    secure: JSXaIocGZtmUZWG45NLgjUop2QPSuVBciJAmJkd0W/JcId3zjkfwTbYHZJ2YVH9+kM9qHqmZwzgCi3DA3qbWTpR7PcwlEXF+whPwoBZ9C1oeIDXMaxb55wkOmaxWUpgncoHa10b039o1b8ta9+0Atn9GASojOe8OdckB03o3mrZTngUj3xwQy0TvXbe6nid3JjBMT42/9zUjsBmOZsyc9FfZ9ONousgk8Xgghaz9nBYcZJIscZg5GeytYRgZQG9V+erjWlfv31W5TedTuO6oNn6MkXSHJ5JeTLBUqdCpdvpjIF6YejjGES3tK8fpWEN6igLrDpidwbDf6fBeVuf4qLT/T5k4DghqAyCR82vv0uvHtXV75MDCe0fWr9lo4YvtxKlqGQ4JGfkTzDhA/8PbzoiifYIH+Z9ui9VCQ7xKUXfJt1tq37kFloCnHclpOYStBDoqledeRF/6BMS0JYKVQeaYfz1HssWeEhOclRaIVJyi7HMzbBDziVyHqcU1I+4ot3wow2bCHAcYLT1Ls1J/TEmgF3EHqEaFdAduOggS17k4zj2enUrkgJGT9/gDDX1PChlGxeIn1/VWhUjekC0k3BngMIeydIO6izeHftXaq2cXL92MZJsJaz9onq1FJenfkHBiU2LY11UEo4I4RAM5INL9tdvGISQAdAgbcIF5Mms=
